version: '3.8'
services:
  # python app
  app:
    build: ./app
    container_name: 'app'
    restart: 'on-failure'
    volumes:
      - type: 'bind'
        source: './app'
        target: '/app'
    depends_on:
      - pgdb

  #POSTGRES
  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    environment:     
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    volumes:
      - type: 'bind'
        source: './dbdata'
        target: '/var/lib/postgresql/data'
      - ./db/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql

  #PGADMIN
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    restart: always
    
volumes:
  app:
  pgdb:

 