version: '3.8'
services:
  # python app
  app:
    build: ./app
    container_name: 'app'
    restart: 'always'
    volumes:
      - type: 'bind'
        source: './app'
        target: '/app'
    depends_on:
      - pgdb

  #POSTGRES
  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    environment:     
      - POSTGRES_DATABASE=ishares
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    volumes:
      - type: 'bind'
        source: './dbdata'
        target: '/var/lib/postgresql/data'
      # - ./postgres_data:/var/lib/postgresql/data
      - ./db/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql

  #PGADMIN
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    restart: always
    
volumes:
  app:
  pgdb:

 